#!/usr/bin/bash

while [[ $# > 1 ]]
do
key="$1"

case $key in
    -u|--user)
    GITHUB_USER="$2"
    shift
    ;;
    -b|--branch)
    BRANCH="$2"
    shift
    ;;
    -i|--image)
    IMAGE="$2"
    shift
    ;;
    *)
            # unknown option
    ;;
esac
shift
done

source set_variables

generate_miq_install_parameters=""

if [ -n "$GITHUB_USER" ]; then
    generate_miq_install_parameters="$generate_miq_install_parameters --user $GITHUB_USER"
fi

if [ -n "$BRANCH" ]; then
    generate_miq_install_parameters="$generate_miq_install_parameters --branch $BRANCH"
fi

./generate_miq_install $generate_miq_install_parameters
./miq_build_image --image $IMAGE --password smartvm
./miq_provision --image $IMAGE --miq-vm-name $MIQ_VM_NAME

# to set MIQ_IP
source set_variables

setup_routing_params=""
wait_for_miq_params=""

if [ -n "$INSTACK_IP" ]; then
    setup_routing_params="$setup_routing_params --instack-ip $INSTACK_IP"
fi

if [ -n "$MIQ_IP" ]; then
setup_routing_params="$setup_routing_params --miq-ip $MIQ_IP"
wait_for_miq_params="$wait_for_miq_params --miq-ip $MIQ_IP"
fi

if [ -n "$HOST_IP" ]; then
setup_routing_params="$setup_routing_params --host-ip $HOST_IP"
fi

./setup_routing $setup_routing_params

./wait_for_miq $setup_routing_params

source set_variables

# register instack undercloud in miq as OpenstackInfra Provider
./miq_register_instack --miq-ip $MIQ_IP --instack-ip $INSTACK_IP --os-username $OS_USERNAME --os-password $OS_PASSWORD --ssh-username $SSH_USERNAME --ssh-key "$SSH_KEY"

./print_info --instack-ip $INSTACK_IP --miq-ip $MIQ_IP --host-ip $HOST_IP
