#!/usr/bin/bash

while [[ $# > 1 ]]
do
key="$1"

case $key in
    -i|--image)
    MIQ_IMAGE="$2"
    shift
    ;;
    -p|--password)
    PASSWORD="$2"
    shift
    ;;
    *)
            # unknown option
    ;;
esac
shift
done

PASSWORD=${PASSWORD:-test}

export LIBGUESTFS_BACKEND=direct
virt-customize -a $MIQ_IMAGE --root-password password:$PASSWORD --firstboot miq_install

