#!/usr/bin/bash

# wait till network is up
sleep 10

# allow port for MIQ
sudo firewall-cmd --add-port 3000/tcp
# allow port for POSTGRESQL
sudo firewall-cmd --add-port 5432/tcp

sudo systemctl start memcached
sudo systemctl enable memcached

sudo systemctl start postgresql
sudo systemctl enable postgresql
sudo -u postgres psql -c "CREATE ROLE root SUPERUSER LOGIN PASSWORD 'smartvm'"

git clone -b %BRANCH% https://github.com/%GITHUB_USER%/manageiq.git
cd manageiq
gem install bundler
bundle install --without qpid:metric_fu
cp config/database.pg.yml config/database.yml
cp certs/v2_key.dev certs/v2_key
bundle exec rake evm:db:reset
bundle exec rake db:seed 
HOME=/root bundle exec rake evm:start
