#!/usr/bin/bash

while [[ $# > 1 ]]
do
key="$1"

case $key in
    -i|--image)
    MIQ_IMAGE="$2"
    shift
    ;;
    -p|--password)
    PASSWORD="$2"
    shift
    ;;
    *)
            # unknown option
    ;;
esac
shift
done

PASSWORD=${PASSWORD:-test}

export LIBGUESTFS_BACKEND=direct
# inject ssh-key
SSH_KEY=$(cat ~/.ssh/id_rsa.pub)
TARGET_SSH_KEY_DIR=/root/.ssh
TARGET_SSH_KEY_FILE=$TARGET_SSH_KEY_DIR/authorized_keys
TARGET_SSHD_CONFIG_FILE=/etc/ssh/sshd_config
TARGET_PSQL_CONFIG_FILE=/var/lib/pgsql/data/postgresql.conf
TARGET_PSQL_HBA_CONFIG_FILE=/var/lib/pgsql/data/pg_hba.conf

virt-builder fedora-21 \
    --size 15G \
    --format qcow2 \
    --output $MIQ_IMAGE \
    --install postgresql-devel,postgresql-server,lsof \
    --mkdir $TARGET_SSH_KEY_DIR \
    --write $TARGET_SSH_KEY_FILE:"$SSH_KEY" \
    --run-command "echo >> $TARGET_SSH_KEY_FILE" \
    --chmod 0644:$TARGET_SSH_KEY_FILE \
    --run-command "sh -c 'echo postgres:smartvm | chpasswd'" \
    --run-command "sudo -u postgres initdb -E UTF8 -D /var/lib/pgsql/data" \
    --edit $TARGET_SSHD_CONFIG_FILE:'s/#?PubkeyAuthentication\s+.*/PubkeyAuthentication yes/' \
    --edit $TARGET_PSQL_CONFIG_FILE:"s/#?listen_addresses\s+=\s+'localhost'/listen_addresses = '*'/" \
    --run-command "echo 'host    all             all             .redhat.com            trust' >> $TARGET_PSQL_HBA_CONFIG_FILE" \
    --root-password password:$PASSWORD \
    --firstboot miq_install

# we need to relabel files to have correct selinux labels
# there is a bug with selinux relabeling with virt-* tools when used with network - 
# temporaly injected /etc/resolv.conf needed for network when modifying image
# is left with bad selinux label and NetworkManager cannot work with that after
# VM boots fromthat image
virt-customize -a $MIQ_IMAGE --no-network \
    --run-command 'setfiles -W -v /etc/selinux/targeted/contexts/files/file_contexts /'

