#!/usr/bin/bash

while [[ $# > 1 ]]
do
key="$1"

case $key in
    -u|--user)
    GITHUB_USER="$2"
    shift
    ;;
    -b|--branch)
    BRANCH="$2"
    shift
    ;;
    -i|--image)
    IMAGE="$2"
    shift
    ;;
    *)
            # unknown option
    ;;
esac
shift
done

MIQ_VM_NAME=miq
DEV=$(ip r | grep default | awk {'print $5'})
HOST_IP=$(ip a s dev $DEV | grep 'inet ' | awk {'print $2'} | awk -F '/' {'print $1'})

INSTACK_IP=$(cat /var/lib/libvirt/dnsmasq/default.leases | grep $(tripleo get-vm-mac instack) | awk '{print $3;}')

./generate_miq_install --user $GITHUB_USER --branch $BRANCH
./miq_build_image --image $IMAGE --password blackmagic
./miq_provision --image $IMAGE --miq-vm-name $MIQ_VM_NAME

MIQ_IP=$(cat /var/lib/libvirt/dnsmasq/default.leases | grep $(tripleo get-vm-mac $MIQ_VM_NAME) | awk '{print $3;}')

./setup_routing --instack-ip $INSTACK_IP --miq-ip $MIQ_IP --host-ip $HOST_IP
./wait_for_miq --miq-ip $MIQ_IP

STACKRC=$(ssh root@$INSTACK_IP 'cat stackrc')
OS_PASSWORD=$(echo "$STACKRC" | grep OS_PASSWORD | awk -F= '{print $2}')
OS_USERNAME=$(echo "$STACKRC" | grep OS_USERNAME | awk -F= '{print $2}')

# register instack undercloud in miq as OpenstackInfra Provider
curl -u admin:smartvm -X POST http://$MIQ_IP:3000/api/providers -H "Content-Type: application/json" -H "Accept: application/json" -d '{"type":"EmsOpenstackInfra","name":"OpenstackInfra Instack","hostname":"'"$INSTACK_IP"'","ipaddress":"'"$INSTACK_IP"'","credentials":[{"userid":"'"$OS_USERNAME"'","password":"'"$OS_PASSWORD"'"}]}'

./print_info --instack-ip $INSTACK_IP --miq-ip $MIQ_IP --host-ip $HOST_IP
