#!/usr/bin/bash

while [[ $# > 1 ]]
do
key="$1"

case $key in
    -i|--instack-ip)
    INSTACK_IP="$2"
    shift
    ;;
    -m|--miq-ip)
    MIQ_IP="$2"
    shift
    ;;
    -h|--host-ip)
    HOST_IP="$2"
    shift
    ;;
    *)
            # unknown option
    ;;
esac
shift
done


echo "ManageIQ dashboard: http://$HOST_IP:3000" 
echo "ManageIQ VM: SSH access:" 
echo "ssh admin@$MIQ_IP from this host; password smartvm"
echo "ssh admin@$HOST_IP -p 2901 from outside; password smartvm"
