#!/usr/bin/bash

MIQ_VM_NAME=miq
DEV=$(ip r | grep default | awk {'print $5'})
HOST_IP=$(ip a s dev $DEV | grep 'inet ' | awk {'print $2'} | awk -F '/' {'print $1'})


INSTACK_IP=$(cat /var/lib/libvirt/dnsmasq/default.leases | grep $(tripleo get-vm-mac instack) | awk '{print $3;}')

if test -n "$INSTACK_IP"; then
	OS_USERNAME=$(ssh root@$INSTACK_IP 'source stackrc; echo $OS_USERNAME')
	OS_PASSWORD=$(ssh root@$INSTACK_IP 'source stackrc; echo $OS_PASSWORD')
	OS_AUTH_URL=$(ssh root@$INSTACK_IP 'source stackrc; echo $OS_AUTH_URL')
	OS_AUTH_IP=$(echo $OS_AUTH_URL | sed -n 's/\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}/\nip&\n/gp' | grep ip | sed 's/ip//')
fi

if test -n "$MIQ_VM_NAME"; then
	MIQ_IP=$(cat /var/lib/libvirt/dnsmasq/default.leases | grep $(tripleo get-vm-mac $MIQ_VM_NAME) | awk '{print $3;}')
fi

if test -n "$INSTACK_IP"; then
	SSH_USERNAME='heat-admin'
	SSH_KEY=$(echo '"'$(ssh root@$INSTACK_IP 'cat /home/stack/.ssh/id_rsa')'"' | json_reformat)
fi
