#!/usr/bin/bash

while [[ $# > 1 ]]
do
key="$1"

case $key in
    -i|--instack-ip)
    INSTACK_IP="$2"
    shift
    ;;
    -m|--miq-ip)
    MIQ_IP="$2"
    shift
    ;;
    -h|--host-ip)
    HOST_IP="$2"
    shift
    ;;
    *)
            # unknown option
    ;;
esac
shift
done

sudo systemctl stop firewalld
sudo systemctl disable firewalld
sudo iptables -F 
sudo iptables -F -t nat
sudo systemctl restart libvirtd

sleep 5

sudo iptables -D FORWARD -o virbr0 -j REJECT --reject-with icmp-port-unreachable
sudo iptables -D FORWARD -i virbr0 -j REJECT --reject-with icmp-port-unreachable

sudo iptables -D POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -j MASQUERADE -t nat
sudo iptables -D POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p tcp -j MASQUERADE --to-ports 1024-65535 -t nat
sudo iptables -D POSTROUTING -s 192.168.122.0/24 ! -d 192.168.122.0/24 -p udp -j MASQUERADE --to-ports 1024-65535 -t nat

sudo iptables -A POSTROUTING -s 192.168.122.0/24 ! -d 192.0.2.0/24 -j MASQUERADE -t nat
sudo iptables -A POSTROUTING -s 192.168.122.0/24 ! -d 192.0.2.0/24 -p tcp -j MASQUERADE --to-ports 1024-65535 -t nat
sudo iptables -A POSTROUTING -s 192.168.122.0/24 ! -d 192.0.2.0/24 -p udp -j MASQUERADE --to-ports 1024-65535 -t nat

if [ -n "$INSTACK_IP" ]; then
    sudo iptables -t nat -A PREROUTING -p tcp -d $HOST_IP --dport 2900 -j DNAT --to-destination $INSTACK_IP:22
    sudo iptables -t nat -A PREROUTING -p tcp -d $HOST_IP --dport 80 -j DNAT --to-destination $INSTACK_IP:80
    sudo ip route add 192.0.2.0/24 via $INSTACK_IP
fi

if [ -n "$MIQ_IP" ]; then
    sudo iptables -t nat -A PREROUTING -p tcp -d $HOST_IP --dport 3000 -j DNAT --to-destination $MIQ_IP:3000
    sudo iptables -t nat -A PREROUTING -p tcp -d $HOST_IP --dport 2901 -j DNAT --to-destination $MIQ_IP:22
    sudo iptables -t nat -A PREROUTING -p tcp -d $HOST_IP --dport 15432 -j DNAT --to-destination $MIQ_IP:5432
fi
